//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soitin2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsSet
    {
        public int Id { get; set; }
        public int playlistquota { get; set; }
        public int numberoftracks { get; set; }
        public int supplementalplaylistquota { get; set; }
    }
}
