//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soitin2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackSet
    {
        public int Id { get; set; }
        public string album { get; set; }
        public string title { get; set; }
        public string track { get; set; }
        public string artist { get; set; }
        public string genre { get; set; }
        public string filename { get; set; }
        public Nullable<int> runningtime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> weight { get; set; }
    }
}
